dist: trusty
language: python
python: 2.7
notifications:
  slack:
    on_success: never
services:
- postgresql
- rabbitmq
apt: # copied from wannier90's travis.yml
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
addons:
  postgresql: '9.5'
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_6bf0778859c5_key -iv $encrypted_6bf0778859c5_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
- sudo apt-get install locate
- sudo service postgresql stop
- sudo apt-get remove postgresql
- sudo apt-get install postgresql-9.5
- sudo updatedb
install:
- pip install -U pip wheel setuptools
- pip install -e git+https://github.com/aiidateam/aiida_core@develop#egg=aiida-core[testing]
- pip install -e git+https://github.com/JuDFTteam/masci-tools@master#egg=masci-tools
- pip install -e .
- pip install codecov
env:
- TEST_TYPE="unittests"
script:
- cd ./aiida_kkr/tests/ && ./run_all.sh
- cd ../../
#- mkdir -m 700 ~/.ssh/
- mv id_rsa_travis ~/.ssh/id_rsa 
- chmod 400 ~/.ssh/id_rsa
- echo "iffgit.fz-juelich.de,134.94.161.83 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH2UDrT0bZP+WmJGGbtLPtFyC5FgQgOM1XvVJ6u5XBJrYMnKNVb9jAttL+k8VvDgcK6b3dFJnvt7eiXtG/hnqCo=" >> ~/.ssh/known_hosts
- git clone gitlab@iffgit.fz-juelich.de:kkr/jukkr.git
after_success:
- codecov
git:
  depth: 3
