dist: trusty
#sudo: required
language: python

python: 2.7

notifications:
  slack:
    on_success: never

services:
    - postgresql
    - rabbitmq

addons:
    postgresql: "9.5"

cache: pip

before_install:  # copied from pgtest's travis.yml
    - sudo apt-get install locate
    - sudo service postgresql stop
    - sudo apt-get remove postgresql
    - sudo apt-get install postgresql-9.5
    - sudo updatedb

install:
    - pip install -U pip wheel setuptools
    - pip install -e git+https://github.com/aiidateam/aiida_core@develop#egg=aiida-core[testing]
    - pip install -e git+https://github.com/JuDFTteam/masci-tools@master#egg=masci-tools
    - pip install -e .

env:
    - TEST_TYPE="unittests"

script: 
    - cd ./aiida_kkr/tests/ && ./run_all.sh

after_success:
    - coveralls

git:
  depth: 3
