dist: trusty
language: python
python: 2.7
notifications:
  slack:
    on_success: never
services:
- postgresql
- rabbitmq
addons:
  postgresql: '9.5'
  apt: # copied from wannier90's travis.yml
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
cache: pip
before_install:
# this decripts the ssh key needed to download the KKR code
- openssl aes-256-cbc -K $encrypted_6bf0778859c5_key -iv $encrypted_6bf0778859c5_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
# Now we install the needed dependencies
- sudo apt-get install locate
- sudo service postgresql stop
- sudo apt-get remove postgresql
- sudo apt-get install postgresql-9.5
- sudo updatedb
install: # python installations
- pip install -U pip wheel setuptools
- pip install -e .
- pip install codecov
env:
- TEST_TYPE="unittests"
script:
# Clone JuKKR repository and build codes
# place the key where it is expected and make sure the connection works passwordless
- mv id_rsa_travis ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
- echo "iffgit.fz-juelich.de,134.94.161.83 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH2UDrT0bZP+WmJGGbtLPtFyC5FgQgOM1XvVJ6u5XBJrYMnKNVb9jAttL+k8VvDgcK6b3dFJnvt7eiXtG/hnqCo=" >> ~/.ssh/known_hosts
# clone the code and install
- ./jukkr_installation.sh
# Now run all tests
- pwd; cd ../aiida_kkr/tests/ && ./run_all.sh
allow_failures:
  - pytest -s --cov-report=term-missing --cov=aiida_kkr -k Test_dos_workflow
  - pytest -s --cov-report=term-missing --cov=aiida_kkr -k Test_gf_writeout_workflow
# (needs allow failure so that after_success is executed)
after_success:
- codecov
#deploy to pypi
#- pip install poetry && poetry publish --build -u XXXXX -p XXXXXX
git:
  depth: 3
